/* trusted.js — real input via the Chrome DevTools Protocol.
 *
 * Synthetic events carry isTrusted:false, and an app is free to ignore them.
 * Events dispatched through CDP are generated by the browser itself, so they
 * are indistinguishable from a human using the mouse and keyboard.
 *
 * The debugger is attached only while a run is active and detached the moment
 * it ends, so Chrome's "being debugged" banner is never left hanging around.
 *
 * Loaded by background.js (service worker), because chrome.debugger is not
 * available to content scripts.
 */

const PROTOCOL_VERSION = '1.3';

const state = {
  tabId: null,
  attached: false,
  attaching: null
};

function debuggee() {
  return { tabId: state.tabId };
}

function send(method, params = {}) {
  return new Promise((resolve, reject) => {
    chrome.debugger.sendCommand(debuggee(), method, params, (result) => {
      const err = chrome.runtime.lastError;
      if (err) reject(new Error(err.message));
      else resolve(result);
    });
  });
}

export function isAttached(tabId) {
  return state.attached && state.tabId === tabId;
}

export function attachedTab() {
  return state.attached ? state.tabId : null;
}

/* Chrome only detaches automatically when a tab closes — not when it navigates,
 * reloads, or when the service worker restarts. Any of those would strand the
 * "being debugged" banner on a tab with no run behind it, so sweep for
 * attachments we no longer have a reason to hold. */
export async function detachStale() {
  const targets = await new Promise((resolve) => {
    try { chrome.debugger.getTargets((t) => resolve(t || [])); }
    catch (_) { resolve([]); }
  });
  for (const t of targets) {
    if (!t.attached || t.type !== 'page' || typeof t.tabId !== 'number') continue;
    if (state.attached && t.tabId === state.tabId) continue;
    await new Promise((resolve) => {
      chrome.debugger.detach({ tabId: t.tabId }, () => { void chrome.runtime.lastError; resolve(); });
    });
  }
}

export async function attach(tabId) {
  if (state.attached && state.tabId === tabId) return true;
  if (state.attached) await detach();
  if (state.attaching) return state.attaching;

  state.attaching = new Promise((resolve, reject) => {
    chrome.debugger.attach({ tabId }, PROTOCOL_VERSION, () => {
      const err = chrome.runtime.lastError;
      if (err) {
        state.attaching = null;
        // Another debugger (usually DevTools) already owns this tab.
        reject(new Error(
          /already attached/i.test(err.message)
            ? 'Chrome DevTools is open on this tab. Close DevTools and try again.'
            : err.message
        ));
        return;
      }
      state.tabId = tabId;
      state.attached = true;
      state.attaching = null;
      resolve(true);
    });
  });
  return state.attaching;
}

export async function detach() {
  if (!state.attached) return;
  const target = debuggee();
  state.attached = false;
  state.tabId = null;
  await new Promise((resolve) => {
    chrome.debugger.detach(target, () => { void chrome.runtime.lastError; resolve(); });
  });
}

/* Chrome hands the tab back to the user if the debugger goes away for any
 * reason; make sure our bookkeeping agrees. */
chrome.debugger.onDetach.addListener((source) => {
  if (source.tabId === state.tabId) {
    state.attached = false;
    state.tabId = null;
  }
});

/* --------------------------------------------------------------- gestures */

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

export async function click(x, y) {
  // Move first: hover state matters to some handlers, and it makes the press
  // look like a real approach rather than a teleport.
  await send('Input.dispatchMouseEvent', { type: 'mouseMoved', x, y, buttons: 0 });
  await sleep(30);
  await send('Input.dispatchMouseEvent', {
    type: 'mousePressed', x, y, button: 'left', buttons: 1, clickCount: 1
  });
  await sleep(40);
  await send('Input.dispatchMouseEvent', {
    type: 'mouseReleased', x, y, button: 'left', buttons: 0, clickCount: 1
  });
}

/* Input.insertText is what the browser uses for IME and paste — it reaches a
 * rich editor exactly the way real composition does. */
export async function insertText(text) {
  await send('Input.insertText', { text });
}

export async function key(keyName) {
  const map = {
    Enter: { windowsVirtualKeyCode: 13, code: 'Enter', key: 'Enter', text: '\r' },
    Backspace: { windowsVirtualKeyCode: 8, code: 'Backspace', key: 'Backspace' },
    Escape: { windowsVirtualKeyCode: 27, code: 'Escape', key: 'Escape' }
  };
  const k = map[keyName];
  if (!k) throw new Error('unmapped key ' + keyName);
  await send('Input.dispatchKeyEvent', { type: 'keyDown', ...k });
  await send('Input.dispatchKeyEvent', { type: 'keyUp', ...k });
}

export async function selectAll() {
  const mod = navigator.userAgent.includes('Mac') ? 4 /* Meta */ : 2 /* Ctrl */;
  const base = { windowsVirtualKeyCode: 65, code: 'KeyA', key: 'a', modifiers: mod };
  await send('Input.dispatchKeyEvent', { type: 'keyDown', ...base });
  await send('Input.dispatchKeyEvent', { type: 'keyUp', ...base });
}
